name: Android General Build CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decode Signature
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SIGNATURE_PASSWORD }}" --output sign.jks signature.jks.gpg

      - name: Dependencies
        run: ./gradlew dependencies

      - name: Lint & JVM Checks
        run: ./gradlew check

      - name: Build Release App
        run: ./gradlew assembleRelease
        env:
          HEROES_KEYSTORE_ALIAS: ${{ secrets.HEROES_KEYSTORE_ALIAS }}
          HEROES_KEYSTORE_PASSWORD: ${{ secrets.HEROES_KEYSTORE_PASSWORD }}
          HEROES_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.HEROES_KEYSTORE_PRIVATE_KEY_PASSWORD }}

      - name: Upload result for job
        uses: actions/upload-artifact@v1
        with:
          name: application
          path: app/build/outputs/apk/release/app-release.apk
